server:
  port: 8061

spring:
  application:
    name: User
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourism?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: czxczx3224039710
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
